#Build configuration
images:
  server: quay.io/infinispan/server:13.0
#Deployment configuration
deploy:
  #Add a user with full security authorization.
  security:
    batch: "user create admin -p changeme"
  #Create a cluster with two pods.
  replicas: 1
  container:
    storage:
      ephemeral: true
