apiVersion: batch/v1
kind: Job
metadata:
  name: import-movies
spec:
  template:
    spec:
      containers:
      - name: import-movies-container
        image: quay.io/lordofthejars/popular-movie-store-quarkus:importer
        imagePullPolicy: Always
        env:
        - name: API_MOVIEDB_KEY
          value: "set_key" 
      restartPolicy: Never